# Numpy
* https://numpy.org/numpy-tutorials/
* numpy: Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이는 자료형이 1가지만 들어감

# 차원
* 0차원 = 점, 스칼라 a=10
* 1차원 = 선 ----- 벡터, 배열, list, tuple [1,2,3,4]
    *벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, Dataframe, matrix, 행렬
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체
* 4차원 = 3차원 요소가 2개 이상
* 5차원 = 4차원 요소가 2개 이상

* numpy는 외부 메서드
* conda install numpy

In [ ]:
# numpy는 외부 패키지이므로 설치 필요
# pip install numpy
# conda install numpy

In [3]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
# 스칼라 데이터
s=10

In [5]:
s.ndim #차원이 없음

AttributeError: 'int' object has no attribute 'ndim'

In [6]:
a.ndim

1

In [7]:
#방향이 없는 벡터
a.shape #5행

(5,)

In [8]:
#세로로 방향을 가진 열벡터
a2=np.array([[1],[2],[3],[4],[5]])
a2.shape

(5, 1)

In [9]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
#행벡터
a3=np.array([[1,2,3,4,5]])
a3

array([[1, 2, 3, 4, 5]])

In [11]:
a3.shape

(1, 5)

In [12]:
#2차원 데이터 = matrix
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
c.ndim

2

In [14]:
c.shape

(2, 5)

In [16]:
#3차원 데이터
d=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]],
          [[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [17]:
d.ndim

3

In [18]:
d.shape

(4, 2, 5)

In [20]:
e=np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],
          [[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [21]:
e.ndim

4

In [22]:
e.shape

(2, 2, 2, 5)

In [28]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [25]:
f[0]

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [29]:
f[1]=f[1]+5
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]],


        [[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]]]])

# numpy에서 자주 사용하는 메서드
* .ndim : 몇 차원인지 보는 것
* .shqpe: 몇 라원, 몇 행, 몇 열로 되어 있는지 구조 확인
* .size: 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

In [30]:
# 5차원 데이터 요소에 10 곱하기
fifth = np.array([[[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                 [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]],
                 [[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                 [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [31]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

In [33]:
fifth.shape

(2, 2, 2, 2, 3)

In [34]:
fifth.size

48

In [35]:
fifth.dtype

dtype('int64')

In [36]:
e=np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [1]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [4]:
# e = np.array([1,2,3,4,5])
e = np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [5]:
e2 = np.array((1, 2, 3.14, 4, 5))
print(e2)
e2.dtype

[1.   2.   3.14 4.   5.  ]


dtype('float64')

In [6]:
e3 = np.array((True, 1, 2, 3.14, "4", 5))
print(e3)
print(e3.dtype)
print(e3[2].dtype)

['True' '1' '2' '3.14' '4' '5']
<U32
<U1


* np.arange(시작,끝,step)

In [7]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [9]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

* .reshape(행, 열)

In [10]:
# .reshape(행, 열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20, 5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [11]:
a4

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

* flatten()

In [12]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
print(a4)
a4.flatten()

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [14]:
a72 = a7.flatten()
a72

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
a73 = a72.reshape(3,2,2,2)
a73

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [16]:
# np.flip() 행렬의 순서를 뒤집을 때
print(a73)
np.flip(a73)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

* np.linspace(시작, 끝, 구간 수)

In [17]:
# np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [19]:
# 정렬, .sort(), sorted()
f = np.array([5 , 7 , 11, 1 , 3, 2, 54, 0, 0.5, 68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

* np.sort

In [39]:
arr=np.array([
    [[5,2,8],
    [1,6,7]],
    
    [[4,9,3],
    [0,2,1]]
])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]
3
(2, 2, 3)


In [41]:
# axis = -1 : 가장 안쪽 차원 1차원 배열을 정렬
print(arr)
np.sort(arr)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[2, 5, 8],
        [1, 6, 7]],

       [[3, 4, 9],
        [0, 1, 2]]])

In [42]:
# axis=1 : 열 별로 정렬 (1,2번째 3,4번째 줄 세로방향 비교)
np.sort(arr,axis=1)

array([[[1, 2, 7],
        [5, 6, 8]],

       [[0, 2, 1],
        [4, 9, 3]]])

In [43]:
np.sort(arr,axis=0)

array([[[4, 2, 3],
        [0, 2, 1]],

       [[5, 9, 8],
        [1, 6, 7]]])

* argsort()

In [20]:
# argsort() 자료중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [21]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

* np.where(조건,참,거짓) 3항 연산

In [45]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
np.where(num%2==0, '짝수','홀수')

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

# 배열 합치기 np.concatenate()

In [47]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a, a.shape)
print(b, b.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)


* np.concatenate((a,b))
* 합치는 기본 방향은 axis=0 행이 늘어남 (아래로 붙음)
* axis=1 열이 늘어남(옆으로 붙음)

## 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [48]:
c=np.array([5,6])
print(c,c.ndim,c.shape)

[5 6] 1 (2,)


In [49]:
np.concatenate((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
d=np.array([[7,8,9]])
e=np.array([[1,2,3],[4,5,6]])
np.concatenate((d,e))

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
f=np.array([[1,2],[3,4],[5,6]])
print(f)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
np.concatenate(e,f)

TypeError: only integer scalar arrays can be converted to a scalar index

In [55]:
# 전치행렬: 행과 열을 바꿈
# .T or .transpose()
print(f)
print(f.shape)
print(f.T)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 3 5]
 [2 4 6]]


# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스와 벡터 연신 시 자동으로 행렬 크기를 맞춰 주는 것

In [57]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [62]:
print(a, a.ndim, a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 2 (3, 5)


In [61]:
b=np.array([10,20,30,40,50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [63]:
a+b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])